version: 2

models:
  - name: dim_listings_clean
    description: All listings with cleaned column names and constraint checks
    columns:
      - name: listing_id
        description: '{{ doc("dim_listings_clean__listing_id") }}'
        tests:
          - unique
          - not_null
      - name: host_id
        description: '{{ doc("dim_listings_clean__host_id") }}'
        tests:
          - not_null
          - relationships:
              to: ref("dim_hosts_clean")
              field: host_id
      - name: listing_room_type
        tests:
          - accepted_values:
              values:
                ["Entire home/apt", "Private room", "Shared room", "Hotel room"]
      - name: listing_minimum_nights
        description: '{{ doc("dim_listings_clean__minimum_nights") }}'
        tests:
          - non_negative

  - name: dim_hosts_clean
    columns:
      - name: host_id
        description: '{{ doc("dim_hosts_clean__host_id") }}'
        tests:
          - unique
          - not_null

      - name: host_is_superhost
        description: '{{ doc("dim_hosts_clean__host_is_superhost") }}'
